In [4]:
import requests
import pandas as pd

In [5]:
def obtener_monumentos():
    url = "https://datos.madrid.es/egob/catalogo/300356-0-monumentos-ciudad-madrid.csv"
    
    try:
        response = requests.get(url)
        response.raise_for_status()  # Verifica si la solicitud fue exitosa

        # Si la solicitud es exitosa, retorna el contenido en formato CSV
        return response.content

    except requests.exceptions.RequestException as e:
        print("Error al obtener los monumentos:", e)
        return None

In [6]:
contenido_csv = obtener_monumentos()

# Verificar si se obtuvo el contenido y guardarlo en un archivo CSV
if contenido_csv:
    with open("../data/madrid/Monumentos/monumentos.csv", "wb") as archivo_csv:
        archivo_csv.write(contenido_csv)
    print("Se ha guardado el archivo monumentos.csv")

Se ha guardado el archivo monumentos.csv

In [7]:
df = pd.read_csv("../data/madrid/Monumentos/monumentos.csv", sep=";", encoding="latin-1")

In [8]:
df

,PK,NOMBRE,SUBTIPO,DESCRIPCION,FECHA,AUTORES,PDF,CONTENT-URL,NOMBRE-VIA,CLASE-VIAL,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 31
0,409634,A las víctimas del Holocausto,Escultura conceptual o abstracta,"La obra, creada por el escultor judío de orige...",2005,"NAHÓN BENGIO, Samuel - STISIN, Alberto",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,TRES CULTURAS,JARDIN,...,DISTRITO,448830.0,4479469.0,40.464322,-3.603558,NaN,NaN,NaN,NaN,
1,409512,A los Abuelos,Grupo Escultórico,"Pequeña escultura, situada en un parque delimi...",1994,"M., Esther",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Alicún,C,...,HORTALEZA,443913.0,4481224.0,40.479812,-3.661719,NaN,NaN,NaN,NaN,
2,408781,A Neruda-El Ser alado,Estatua,Monumento dedicado al escritor Pablo Neruda (1...,1988,"QUETGLÁS, Matías",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,José Luis Ozores,Gta,...,PUENTE DE VALLECAS,444621.0,4470345.0,40.381855,-3.652419,NaN,NaN,NaN,NaN,
3,408836,Abogados Laboristas,"Elemento conmemorativo, Lápida",El 24 de enero de 1977 se produjo un atentado ...,1987,"ROLDÁN PASCUAL, Joaquín",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Atocha,C,...,CENTRO,440608.0,4473823.0,40.412911,-3.700017,NaN,NaN,NaN,NaN,
4,408920,Abstracta I,Escultura conceptual o abstracta,"La histórica quinta de la Fuente del Berro, de...",1992,"GONZÁLEZ CALISAVO, Fernando",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,NaN,NaN,...,SALAMANCA,443926.0,4474987.0,40.421746,-3.662293,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827,409830,Álvaro Iglesias Sánchez,"Elemento conmemorativo, Lápida",El 6 de abril de 1982 se produjo un incendio e...,1982,"JIMÉNEZ, L.",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,CARRANZA,CALLE,...,CENTRO,440358.0,4475611.0,40.429000,-3.703131,NaN,NaN,NaN,NaN,
1828,408375,Ángeles de la Paz,Grupo Escultórico,"Este monumento, proyectado en chapa de hierro ...",1964,"ESPINOS ALONSO, José",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Bruselas,Avda,...,SALAMANCA,443676.0,4477142.0,40.443023,-3.664153,NaN,NaN,NaN,NaN,
1829,409037,Árbol de la Vida,"Puerta, Arco triunfal",El Jardín de las Tres Culturas es un ámbito es...,1990,"ESTEBAN PENELAS, José Luis - ESTERAS MARTÍN, E...",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,TRES CULTURAS,JARDIN,...,DISTRITO,448830.0,4479469.0,40.464322,-3.603558,NaN,NaN,NaN,NaN,
1830,408008,Íñigo Arista,Estatua,Forma parte esta escultura de la serie concebi...,1750,"OÑATE, José",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Oriente,Pza,...,CENTRO,439581.0,4474364.0,40.417710,-3.712172,NaN,NaN,NaN,NaN,
1831,400117,Órgano,Escultura conceptual o abstracta,En 1971 el arquitecto José Luis Picardo ganó e...,1977,"SEMPERE JUAN, Eusebio",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Castelló,C,...,SALAMANCA,442223.0,4475831.0,40.431113,-3.681166,NaN,NaN,NaN,NaN,

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1832 entries, 0 to 1831
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PK             1832 non-null   int64
 1   NOMBRE         1832 non-null   object
 2   SUBTIPO        1832 non-null   object
 3   DESCRIPCION    1831 non-null   object
 4   FECHA          1813 non-null   object
 5   AUTORES        916 non-null    object
 6   PDF            1832 non-null   object
 7   CONTENT-URL    1832 non-null   object
 8   NOMBRE-VIA     1586 non-null   object
 9   CLASE-VIAL     1582 non-null   object
 10  TIPO-NUM       1830 non-null   object
 11  NUM            883 non-null    object
 12  PLANTA         0 non-null      float64
 13  PUERTA         0 non-null      float64
 14  ESCALERAS      0 non-null      float64
 15  ORIENTACION    0 non-null      float64
 16  LOCALIDAD      1829 non-null   object
 17  PROVINCIA      1829 non-null   object
 18  CODIGO-POSTAL  348 non-null    float64
 19  COD-BARRIO     1350 non-null   float64
 20  BARRIO         1696 non-null   object
 21  COD-DISTRITO   1350 non-null   float64
 22  DISTRITO       1829 non-null   object
 23  COORDENADA-X   1829 non-null   float64
 24  COORDENADA-Y   1829 non-null   float64
 25  LATITUD        1776 non-null   float64
 26  LONGITUD       1776 non-null   float64
 27  TELEFONO       0 non-null      float64
 28  FAX            0 non-null      float64
 29  EMAIL          0 non-null      float64
 30  TIPO           0 non-null      float64
 31  Unnamed: 31    1832 non-null   object
dtypes: float64(15), int64(1), object(16)
memory usage: 458.1+ KB

In [10]:
df.dropna(subset=["LONGITUD"], inplace=True)
df.dropna(subset=["LOCALIDAD"], inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PK             1775 non-null   int64
 1   NOMBRE         1775 non-null   object
 2   SUBTIPO        1775 non-null   object
 3   DESCRIPCION    1774 non-null   object
 4   FECHA          1757 non-null   object
 5   AUTORES        877 non-null    object
 6   PDF            1775 non-null   object
 7   CONTENT-URL    1775 non-null   object
 8   NOMBRE-VIA     1579 non-null   object
 9   CLASE-VIAL     1576 non-null   object
 10  TIPO-NUM       1775 non-null   object
 11  NUM            880 non-null    object
 12  PLANTA         0 non-null      float64
 13  PUERTA         0 non-null      float64
 14  ESCALERAS      0 non-null      float64
 15  ORIENTACION    0 non-null      float64
 16  LOCALIDAD      1775 non-null   object
 17  PROVINCIA      1775 non-null   object
 18  CODIGO-POSTAL  348 non-null    float64
 19  COD-BARRIO     1299 non-null   float64
 20  BARRIO         1642 non-null   object
 21  COD-DISTRITO   1299 non-null   float64
 22  DISTRITO       1774 non-null   object
 23  COORDENADA-X   1774 non-null   float64
 24  COORDENADA-Y   1774 non-null   float64
 25  LATITUD        1775 non-null   float64
 26  LONGITUD       1775 non-null   float64
 27  TELEFONO       0 non-null      float64
 28  FAX            0 non-null      float64
 29  EMAIL          0 non-null      float64
 30  TIPO           0 non-null      float64
 31  Unnamed: 31    1775 non-null   object
dtypes: float64(15), int64(1), object(16)
memory usage: 457.6+ KB

In [12]:
df = df.drop(["PDF","CONTENT-URL","TIPO-NUM","PLANTA","PUERTA","ESCALERAS","ORIENTACION","LOCALIDAD","PROVINCIA",
              "CODIGO-POSTAL","COD-BARRIO","COD-DISTRITO","TELEFONO","FAX","EMAIL","TIPO","Unnamed: 31"],axis=1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PK            1775 non-null   int64
 1   NOMBRE        1775 non-null   object
 2   SUBTIPO       1775 non-null   object
 3   DESCRIPCION   1774 non-null   object
 4   FECHA         1757 non-null   object
 5   AUTORES       877 non-null    object
 6   NOMBRE-VIA    1579 non-null   object
 7   CLASE-VIAL    1576 non-null   object
 8   NUM           880 non-null    object
 9   BARRIO        1642 non-null   object
 10  DISTRITO      1774 non-null   object
 11  COORDENADA-X  1774 non-null   float64
 12  COORDENADA-Y  1774 non-null   float64
 13  LATITUD       1775 non-null   float64
 14  LONGITUD      1775 non-null   float64
dtypes: float64(4), int64(1), object(10)
memory usage: 221.9+ KB

In [14]:
df[df["CLASE-VIAL"].isna()]

,PK,NOMBRE,SUBTIPO,DESCRIPCION,FECHA,AUTORES,NOMBRE-VIA,CLASE-VIAL,NUM,BARRIO,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD
4,408920,Abstracta I,Escultura conceptual o abstracta,"La histórica quinta de la Fuente del Berro, de...",1992,"GONZÁLEZ CALISAVO, Fernando",NaN,NaN,NaN,FUENTE DEL BERRO,SALAMANCA,443926.0,4474987.0,40.421746,-3.662293
5,408921,Abstracta II,Escultura conceptual o abstracta,"La histórica quinta de la Fuente del Berro, de...",1992,"GONZÁLEZ CALISAVO, Fernando",NaN,NaN,NaN,FUENTE DEL BERRO,SALAMANCA,443819.0,4474803.0,40.421962,-3.662260
22,408575,Al Maestro,Grupo Escultórico,Este monumento fue iniciativa del profesor Jos...,1965,"RÍOS CAMPOS, Víctor de los",NaN,NaN,NaN,CASA DE CAMPO,MONCLOA-ARAVACA,438293.0,4476016.0,40.432498,-3.727513
33,408441,Alfonso R. Castelao,"Elemento conmemorativo, Lápida",En la zona ajardinada que queda entre el Parqu...,1982,NaN,NaN,NaN,NaN,GUINDALERA,SALAMANCA,443964.0,4476305.0,40.435503,-3.660683
34,408005,Alfonso VI,Estatua,Forma parte esta escultura de la serie concebi...,1750,"CORRAL, Felipe del",NaN,NaN,NaN,PALACIO,CENTRO,439434.0,4474590.0,40.419736,-3.713926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785,409488,Vagón-plataforma de tren,Elemento de ornamentación,Elemento ferroviario instalado entre 1991 y 19...,1992,NaN,NaN,NaN,NaN,DELICIAS,ARGANZUELA,441825.0,4471696.0,40.393835,-3.685479
1795,408745,Venus emergiendo de las aguas,Escultura conceptual o abstracta,"La escultura, que representa la figura de una ...",1990,"ARAGONÉS, Ángel",NaN,NaN,NaN,PRADOLONGO,USERA,440354.0,4469539.0,40.372427,-3.703885
1801,409057,Viga,Escultura conceptual o abstracta,"Se trata de una de las obras, en este caso la ...",1991,"DU BON CRUZ, Jorge",NaN,NaN,NaN,CORRALEJOS,BARAJAS,447971.0,4479175.0,40.461618,-3.613677
1803,400079,Virgen Blanca (Virgen del Asedio),Estatua,"La imagen central de este monumento, que repre...",1954,NaN,NaN,NaN,NaN,CIUDAD UNIVERSITARIA,MONCLOA-ARAVACA,438792.0,4476772.0,40.439345,-3.721703
1812,409345,Vías de tren,"Elemento conmemorativo, Lápida",Tramo de vía del antiguo ferrocarril de Argand...,Posterior a 1969,NaN,NaN,NaN,NaN,MARROQUINA,MORATALAZ,445815.0,4473287.0,40.408428,-3.638603

In [15]:
df["DESCRIPCION"] = df["DESCRIPCION"].fillna("No disponible")
df["FECHA"] = df["FECHA"].fillna("No disponible")
df["AUTORES"] = df["AUTORES"].fillna("No disponible")
df["NUM"] = df["NUM"].fillna("No disponible")
df["BARRIO"] = df["BARRIO"].fillna("No disponible")
df["DISTRITO"] = df["DISTRITO"].fillna("No disponible")
df["NOMBRE-VIA"] = df["NOMBRE-VIA"].fillna("No disponible")
df["CLASE-VIAL"] = df["CLASE-VIAL"].fillna("No disponible")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PK            1775 non-null   int64
 1   NOMBRE        1775 non-null   object
 2   SUBTIPO       1775 non-null   object
 3   DESCRIPCION   1775 non-null   object
 4   FECHA         1775 non-null   object
 5   AUTORES       1775 non-null   object
 6   NOMBRE-VIA    1775 non-null   object
 7   CLASE-VIAL    1775 non-null   object
 8   NUM           1775 non-null   object
 9   BARRIO        1775 non-null   object
 10  DISTRITO      1775 non-null   object
 11  COORDENADA-X  1774 non-null   float64
 12  COORDENADA-Y  1774 non-null   float64
 13  LATITUD       1775 non-null   float64
 14  LONGITUD      1775 non-null   float64
dtypes: float64(4), int64(1), object(10)
memory usage: 221.9+ KB

In [17]:
df[df["COORDENADA-X"].isna()]

,PK,NOMBRE,SUBTIPO,DESCRIPCION,FECHA,AUTORES,NOMBRE-VIA,CLASE-VIAL,NUM,BARRIO,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD
1698,408556,Sagrado Corazón de Jesús,Estatua,"Este monumento al Sagrado Corazón, de carácter...",1940,No disponible,No disponible,No disponible,No disponible,CASA DE CAMPO,MONCLOA-ARAVACA,NaN,NaN,40.422842,-3.766396

In [18]:
print(df.loc[1698,"LATITUD"])
print(df.loc[1698,"LONGITUD"])

40.422842
-3.766396

In [19]:
df.loc[1698,"COORDENADA-X"] = 434870.85023828844
df.loc[1698,"COORDENADA-Y"] = 4475005.197228354

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PK            1775 non-null   int64
 1   NOMBRE        1775 non-null   object
 2   SUBTIPO       1775 non-null   object
 3   DESCRIPCION   1775 non-null   object
 4   FECHA         1775 non-null   object
 5   AUTORES       1775 non-null   object
 6   NOMBRE-VIA    1775 non-null   object
 7   CLASE-VIAL    1775 non-null   object
 8   NUM           1775 non-null   object
 9   BARRIO        1775 non-null   object
 10  DISTRITO      1775 non-null   object
 11  COORDENADA-X  1775 non-null   float64
 12  COORDENADA-Y  1775 non-null   float64
 13  LATITUD       1775 non-null   float64
 14  LONGITUD      1775 non-null   float64
dtypes: float64(4), int64(1), object(10)
memory usage: 286.4+ KB

In [21]:
df.head()

,PK,NOMBRE,SUBTIPO,DESCRIPCION,FECHA,AUTORES,NOMBRE-VIA,CLASE-VIAL,NUM,BARRIO,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD
0,409634,A las víctimas del Holocausto,Escultura conceptual o abstracta,"La obra, creada por el escultor judío de orige...",2005,"NAHÓN BENGIO, Samuel - STISIN, Alberto",TRES CULTURAS,JARDIN,No disponible,No disponible,DISTRITO,448830.0,4479469.0,40.464322,-3.603558
1,409512,A los Abuelos,Grupo Escultórico,"Pequeña escultura, situada en un parque delimi...",1994,"M., Esther",Alicún,C,No disponible,APÓSTOL SANTIAGO,HORTALEZA,443913.0,4481224.0,40.479812,-3.661719
2,408781,A Neruda-El Ser alado,Estatua,Monumento dedicado al escritor Pablo Neruda (1...,1988,"QUETGLÁS, Matías",José Luis Ozores,Gta,116,PORTAZGO,PUENTE DE VALLECAS,444621.0,4470345.0,40.381855,-3.652419
3,408836,Abogados Laboristas,"Elemento conmemorativo, Lápida",El 24 de enero de 1977 se produjo un atentado ...,1987,"ROLDÁN PASCUAL, Joaquín",Atocha,C,55,CORTES,CENTRO,440608.0,4473823.0,40.412911,-3.700017
4,408920,Abstracta I,Escultura conceptual o abstracta,"La histórica quinta de la Fuente del Berro, de...",1992,"GONZÁLEZ CALISAVO, Fernando",No disponible,No disponible,No disponible,FUENTE DEL BERRO,SALAMANCA,443926.0,4474987.0,40.421746,-3.662293

In [22]:
# Intercambiamos el orden de las columnas 3 y 4 para luego cambiarles el nombre para favorecer la visualización.
df.iloc[:, [6, 7]] = df.iloc[:, [7, 6]].values

In [23]:
df.rename(columns={"NOMBRE-VIA": "CLASE-VIA", "CLASE-VIAL": "NOMBRE-VIA"}, inplace=True)

In [24]:
df.head()

,PK,NOMBRE,SUBTIPO,DESCRIPCION,FECHA,AUTORES,CLASE-VIA,NOMBRE-VIA,NUM,BARRIO,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD
0,409634,A las víctimas del Holocausto,Escultura conceptual o abstracta,"La obra, creada por el escultor judío de orige...",2005,"NAHÓN BENGIO, Samuel - STISIN, Alberto",JARDIN,TRES CULTURAS,No disponible,No disponible,DISTRITO,448830.0,4479469.0,40.464322,-3.603558
1,409512,A los Abuelos,Grupo Escultórico,"Pequeña escultura, situada en un parque delimi...",1994,"M., Esther",C,Alicún,No disponible,APÓSTOL SANTIAGO,HORTALEZA,443913.0,4481224.0,40.479812,-3.661719
2,408781,A Neruda-El Ser alado,Estatua,Monumento dedicado al escritor Pablo Neruda (1...,1988,"QUETGLÁS, Matías",Gta,José Luis Ozores,116,PORTAZGO,PUENTE DE VALLECAS,444621.0,4470345.0,40.381855,-3.652419
3,408836,Abogados Laboristas,"Elemento conmemorativo, Lápida",El 24 de enero de 1977 se produjo un atentado ...,1987,"ROLDÁN PASCUAL, Joaquín",C,Atocha,55,CORTES,CENTRO,440608.0,4473823.0,40.412911,-3.700017
4,408920,Abstracta I,Escultura conceptual o abstracta,"La histórica quinta de la Fuente del Berro, de...",1992,"GONZÁLEZ CALISAVO, Fernando",No disponible,No disponible,No disponible,FUENTE DEL BERRO,SALAMANCA,443926.0,4474987.0,40.421746,-3.662293

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PK            1775 non-null   int64
 1   NOMBRE        1775 non-null   object
 2   SUBTIPO       1775 non-null   object
 3   DESCRIPCION   1775 non-null   object
 4   FECHA         1775 non-null   object
 5   AUTORES       1775 non-null   object
 6   CLASE-VIA     1775 non-null   object
 7   NOMBRE-VIA    1775 non-null   object
 8   NUM           1775 non-null   object
 9   BARRIO        1775 non-null   object
 10  DISTRITO      1775 non-null   object
 11  COORDENADA-X  1775 non-null   float64
 12  COORDENADA-Y  1775 non-null   float64
 13  LATITUD       1775 non-null   float64
 14  LONGITUD      1775 non-null   float64
dtypes: float64(4), int64(1), object(10)
memory usage: 286.4+ KB

In [26]:
nombre_archivo = "../Json/monumentos.json"

In [27]:
df.to_json(nombre_archivo, orient='records')